apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proyecto-cloud
spec:
  template:
    spec:
      containers:
      - name: backend
        image: facundo676/backend-shop:dev-v2
