apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace destino para dev
namespace: proyecto-cloud-dev

# Referencia a los manifiestos base
resources:
  - ../../base
  - nginx-configmap.yaml

components:
  - frontend-tag.yaml
  - backend-tag.yaml

# Configuración específica para dev
namePrefix: dev-
nameSuffix: -dev

# Patches específicos para dev (menos recursos)
patches:
  - path: deployment_patch.yaml

patchesStrategicMerge:
  - frontend-tag.yaml
  - backend-tag.yaml