apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Run server without TLS (necesario para webhooks cuando usás ngrok/proxy)
  server.insecure: "true"
  
  # Configuración adicional para mejorar la respuesta de webhooks
  server.grpc.web: "true"
  
  # Log level para debug si necesitás (opcional)
  server.log.level: "info"
