apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-cloud-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudo-init-project/infra-app-k8s
    targetRevision: master
    path: overlays/staging  # ✅ Apunta al overlay de staging
  destination:
    server: https://kubernetes.default.svc
    namespace: proyecto-cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
