apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proyectoCloud

resources:
  - namespace.yaml
  - secrets.yaml
  - db/configmap.yaml
  - db/statefulset.yaml
  - db/service.yaml
  - back/deployment.yaml
  - back/service.yaml
  - front/deployment.yaml
  - front/service.yaml

images:
  - name: facundo676/backend-shop
    newTag: latest
  - name: facundo676/frontend-shop
    newTag: latest
