apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: staging-app-secret-stg
  namespace: proyecto-cloud-staging
spec:
  encryptedData:
    jwt-secret: AgBDTsXN4uA+4tm7FAIqdoDIz/gguAz0IOvvjbxOIzIw9+9PCtEU10czq78uSNVDo8M4rCMXBWARFLPTZ6+crvG/v6y3TokEFYceFEdP4vobve+PPvFP+8yoo4p6vbQY9jkmBCSERBy03dF6HmhUFqJa2z53wuAQhHH5h+FToia2x+IMuzsMRNmzQbg4c1Vfych/gQQiS/5vtaJj6zkOemD1xrMXEUznt+6gGdlsaSf06RS0krcYo/Z4j4z07hmatEaba0vA3FjuTQbDvujYqGxEydyH3Ou0dE6YclDqKPds2D1uxCVCctJrU+G/vacSoYyEc2N6bJq1BCJc6KFKBOuYJWCENiuF6YCnXhr6e0z9tife2mjcSGRFZrRsPAtQxTqBr4nMFkgjx7VXL06o3Nh6njcBTHEcq8gsQtWgzY++t+6R9ApHFBn8Cn+K0YqFE1GS+sWkEwu5UdoOcs100n469WtO2GzhqUZOgdcKpUgQ9RmWvv9y1+0IK0TkFdq2v2zXt28OOfW68OmLDctiha9nK9lEmDEIrQxT6MvE/qMGWQc4PFmJHYpvGhj8sGMFRSwdCGERYQtr2Ts0g9cpTKJ+ZWG6vSL+C32H2ajyisN4PwQpw6u72Fr8JiZI0pMxsdaujUmgU9q+CcPMvjUkmR3tO0Xj6EWIsS+9T8i50fu0jawniPQ2qPY2jv7Uh0NbVquVAqEcsRZ29j3cWVHTsgMP/MHKGP9BhM4lP1hXBFd+UiPQrc99F1mdB03gow==
  template:
    metadata:
      creationTimestamp: null
      name: staging-app-secret-stg
      namespace: proyecto-cloud-staging
    type: Opaque
---
