# FRONTEND VERSION - STAGING
# Cambiar image tag para actualizar versión

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proyecto-cloud
spec:
  template:
    spec:
      containers:
      - name: frontend
        image: facundo676/frontend-shop:stg-v1
