apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cambiar namespace destino
namespace: proyecto-cloud-staging

# Referencia a los manifiestos base
resources:
  - ../../base

# Configuración específica para staging
namePrefix: staging-
nameSuffix: -stg

# Patches específicos para staging
patches:
  - path: deployment_patch.yaml

# Imágenes específicas para staging
images:
  - name: facundo676/backend-shop
    newTag: latest
  - name: facundo676/frontend-shop
    newTag: latest
