apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proyecto-cloud-staging

resources:
  - ../../base
  - nginx-configmap.yaml

namePrefix: staging-
nameSuffix: -stg

patches:
  - path: deployment_patch.yaml

patchesStrategicMerge:
  - frontend-tag.yaml
  - backend-tag.yaml
