apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Referencia a los manifiestos base
bases:
  - ../../base

# Configuración específica para staging
namePrefix: staging-
nameSuffix: -stg

# Patches específicos para staging
patchesStrategicMerge:
  - deployment_patch.yaml

# Imágenes específicas para staging (si necesitas diferentes tags)
images:
  - name: facundo676/backend-shop
    newTag: staging-latest
  - name: facundo676/frontend-shop
    newTag: staging-latest
