apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proyecto-cloud-staging

resources:
  - ../../base

namePrefix: staging-
nameSuffix: -stg

patches:
  - path: deployment_patch.yaml

images:
  - name: facundo676/backend-shop
    newTag: latest
  - name: facundo676/frontend-shop
    newTag: latest
