apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proyecto-cloud
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        # Configuración específica para React Router
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        # Headers para SPA
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        
        # API proxy al backend - USAR NOMBRE REAL DEL SERVICIO
        location /api/ {
            proxy_pass http://staging-backend-service-stg:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_send_timeout 5s;
            proxy_read_timeout 5s;
        }
        
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
