apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proyecto-cloud-production

resources:
  - ../../base
  - nginx-configmap.yaml

namePrefix: prod-
nameSuffix: -prod

patches:
  - path: deployment_patch.yaml

patchesStrategicMerge:
  - frontend-tag.yaml
  - backend-tag.yaml