apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: proyecto-cloud-staging
spec:
  encryptedData:
    jwt-secret: AgAil9sOF3BfTn5pl+Q/geaVpO3tbSeOvDzIpkfEQ4aKsBgzlkAj+y2D2U7kTeikrXZsGee+PE+II4hNxB/hsbgjgATL19Rb9ME+KxqSS496Yi/LbXgI9qfjvmWjsQbBhcmsSkbu8RIHOnFdFoM8uCSX0IjNxx+fyHlue2XNrZYZWsEdOmcviGFJt7AzOoeBnoRyj9IUcH+/4QDFvfocBzSnhtx8TUGAW2PejNYV0G8EX9gRRtw9N+wSZWKxeI9ns55Nac/NlePhODJ5LjnISEx13p9sye+AVsmpMoAl7FM8Jc03Mq7wqP0FApeQviZdfro2GH/8WUHfbjB5i8KDK/ocsyYvUiGtO6Y9hee4aYKbZyl6BQNTXHiGXvrKNnf/esQtK/rk3ITHE005UiFCJKMsZvwa94/XKfC9ne+ABYbtWdBJZ2R0X5gk5oHWPrqKimbyN+ETA9ReyxNa9gZuVIK/4Yk1ldboVKrTNLUicdzBcZfstYZdllO1ZWe2hBW3buIqyHVC6feEUNWejbw+BGXhfI28//ci00SAD/eT6sqYq2e61ddbtOLEJFxotFeEM2VpvqbDdk/HpCuOgyrd7TVez9B8BvJG04xIb4/P7S3lDZc0yOHi1PdjBz60/JtSNtdI1jbzCSuLCm9MHyFRj/+Trpe8Kfb4+/vwEzUW4WkSCK8ejiF/bmrSSxa+tlH9psHSzMdkCQQM345B7Anwy4LnLYw+oODMTFtv5VzrKibMF6V3qS+1IRHENtqYlg==
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: proyecto-cloud-staging
---
