apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-cloud-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudo-init-project/Infra-App-K8s
    targetRevision: master
    path: overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: proyecto-cloud-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
