apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: proyecto-cloud
data:
  init.sql: |
    CREATE TABLE `clientes` (
      `id_cliente` int(11) NOT NULL,
      `nombre` varchar(255) NOT NULL,
      `apellido` varchar(255) NOT NULL,
      `fecha_ingreso` varchar(255) NOT NULL,
      `domicilio` varchar(255) NOT NULL,
      `telefono` varchar(15) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `clientes` (`id_cliente`, `nombre`, `apellido`, `fecha_ingreso`, `domicilio`, `telefono`) VALUES
    (1, 'Tomas', 'Matadero', '2025-05-13', 'Avenida Siempre Viva', '261746235');

    CREATE TABLE `productos` (
      `id_producto` int(11) NOT NULL,
      `codigo_ean` varchar(255) NOT NULL,
      `nombre_producto` varchar(255) NOT NULL,
      `descripcion_producto` varchar(255) NOT NULL,
      `tipo` varchar(255) NOT NULL,
      `marca` varchar(255) NOT NULL,
      `precio` double NOT NULL,
      `stock` int(11) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `productos` (`id_producto`, `codigo_ean`, `nombre_producto`, `descripcion_producto`, `tipo`, `marca`, `precio`, `stock`) VALUES
    (1, '9079', 'Vino Tinto', 'Vino tinto de caja', 'tipo marron', 'tinto humilde', 200, 1);

    CREATE TABLE `usuarios` (
      `id_usuario` int(11) NOT NULL,
      `nombre_usuario` varchar(255) NOT NULL,
      `password_usuario` varchar(255) NOT NULL,
      `role` varchar(50) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    INSERT INTO `usuarios` (`id_usuario`, `nombre_usuario`, `password_usuario`, `role`) VALUES
    (1, 'admin', 'admin', 'ADMIN');

    ALTER TABLE `clientes`
      ADD PRIMARY KEY (`id_cliente`);

    ALTER TABLE `productos`
      ADD PRIMARY KEY (`id_producto`);

    ALTER TABLE `usuarios`
      ADD PRIMARY KEY (`id_usuario`),
      ADD UNIQUE KEY `nombre_usuario` (`nombre_usuario`),
      ADD UNIQUE KEY `UKof5vabgukahdwmgxk4kjrbu98` (`nombre_usuario`);

    ALTER TABLE `clientes`
      MODIFY `id_cliente` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

    ALTER TABLE `productos`
      MODIFY `id_producto` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

    ALTER TABLE `usuarios`
      MODIFY `id_usuario` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
