apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: proyecto-cloud
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
