apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: facundo676/frontend-shop
    newTag: latest  # Este tag se actualiza automáticamente por CI/CD espero
