apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: proyecto-cloud
type: Opaque
stringData:
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  root-password: ${MYSQL_ROOT_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: proyecto-cloud
type: Opaque
stringData:
  jwt-secret: ${JWT_SECRET}
